from typing import List, Dict, Any, Optional, ClassVar


class Books:
    _a_one_chapter_books: ClassVar[List[str]]
    _a_psalms_with_heading: ClassVar[List[int]]

    def __init__(self) -> None: ...
    def parse_books(self, xml_file: str) -> List[Dict[str, Any]]: ...
    def get_valid_abbreviations(self) -> List[str]: ...
    def is_valid_abbreviation(self, abbrev: str) -> bool: ...
    @classmethod
    def get_one_chapter_books(cls) -> List[str]: ...
    def get_sort_value(self, abbrev: str) -> int: ...
    def get_max_chapter(self, abbr: str) -> Optional[int]: ...
    def get_max_verse(self, abbr: str, ch: Any) -> Optional[int]: ...
    @classmethod
    def get_psalms_with_heading(cls) -> List[int]: ...
    @classmethod
    def is_psalm_with_heading(cls, ch: Any) -> bool: ...
    def get_testament(self, book: str) -> Optional[str]: ...
    def get_latex_abbrev(self, book: str) -> Optional[str]: ...
