from typing import List, Dict, Any, Optional


class Versions:
    def __init__(self) -> None: ...
    def parse_xml(self, xml_file: str) -> List[Dict[str, Any]]: ...
    def get_versions_filtered(self, vfilter: Optional[List[str]], lfilter: Optional[List[str]], sfilter: Optional[str]) -> List[Dict[str, Any]]: ...
    def get_versions(self) -> List[Dict[str, Any]]: ...
    def get_hosting_server(self, ver: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
